import AuthenticationServices
import CryptoKit
import DyorKit
import Foundation
import os
import UIKit

/// What an authenticator returned from one prompt, before any policy is applied.
struct PasskeyResponse {
    let credentialID: Data
    /// The WebAuthn user handle: generated by the app at registration, returned by every assertion.
    let userID: Data?
    /// Registration only: the provider's `prf.isSupported`, nil when it returned no PRF result (and for assertions).
    let prfSupported: Bool?
    /// PRF output for the first salt of the request.
    let first: Data?
    /// PRF output for the second salt, when the authenticator evaluated it.
    let second: Data?
}

/// One system prompt per call. The system authenticator runs ASAuthorizationController; a DEBUG Simulator build can
/// run the stub instead (StubPasskeyAuthenticator.swift).
@MainActor
protocol PasskeyAuthenticator: AnyObject {
    /// Registers a discoverable, user-verified passkey for `rpId` and evaluates the PRF with both salts in the same prompt.
    func register(rpId: String, name: String, userID: Data, salts: (Data, Data)) async throws -> PasskeyResponse
    /// Asserts with any discoverable passkey for `rpId` (no allowCredentials) or, when `credentialID` is set, only
    /// that one, evaluating the PRF with the given salts.
    func assert(rpId: String, salts: (Data, Data), credentialID: Data?) async throws -> PasskeyResponse
}

/// The passkey ceremonies Mera accounts need, the way Mera's `createPasskeyWithPrfOutput` and `getPasskeyPrfOutput` run
/// them: a discoverable, user-verified platform passkey bound to the relying party, evaluated with two 32-byte salts in
/// the same prompt. The outputs are the only secrets the account layer ever sees, and they live in memory for the
/// duration of a session — nothing is written to disk. The rules (MERA-PLAN §2) are `Mera.Ceremony` in DyorKit:
///
/// - registration with `prf.isSupported == false` stops with `prfUnavailable` and no second prompt;
/// - registration with PRF support but no first output runs one pinned fallback assertion over both salts;
/// - a missing second output is fine: the utility output is fetched with a pinned assertion when first needed;
/// - one ceremony at a time (`exclusive`): a concurrent request fails with `Mera.Ceremony.Busy`.
@MainActor
final class PasskeyCeremony {
    struct Result {
        let credentialID: Data
        /// The passkey's user handle, kept in memory only.
        let userID: Data?
        /// PRF output for Mera's account namespace.
        let account: Data
        /// PRF output for DyorHQ's utility namespace; nil when the authenticator evaluated only one salt.
        let utility: Data?
    }

    enum Failure: LocalizedError {
        case prfUnavailable, cancelled, associationUnavailable, wrongCredential, failed
        var errorDescription: String? {
            switch self {
            case .prfUnavailable: return "This passkey provider can’t create a DyorHQ account: it doesn’t support the passkey feature DyorHQ needs (PRF). Use Passwords (iCloud Keychain) on iOS 18 or later."
            case .cancelled: return "Cancelled."
            case .associationUnavailable: return "Passkeys aren’t set up for DyorHQ on this device yet: iOS couldn’t confirm the app belongs to accounts.dyorhq.fun. Check your connection and try again, or update the app."
            case .wrongCredential: return "The passkey that answered isn’t the one this account uses."
            case .failed: return "The passkey request didn’t complete. Please try again."
            }
        }
    }

    private let authenticator: any PasskeyAuthenticator
    private let gate = Mera.Ceremony.Gate()

    init(authenticator: any PasskeyAuthenticator) {
        self.authenticator = authenticator
    }

    /// Whether a ceremony is open (its system sheet up). Observable through the gate.
    var isBusy: Bool { gate.isBusy }

    /// Runs `body` as the only ceremony in progress. A multi-step ceremony (a registration and its fallback assertion)
    /// runs inside one call; a request made while another is open throws `Mera.Ceremony.Busy` at once.
    func exclusive<T>(_ body: () async throws -> T) async throws -> T {
        try await gate.run(body)
    }

    /// Registers a new passkey: one prompt, both salts, a fresh random user handle. The response may carry no usable
    /// account output; `complete` decides what follows.
    func register(rpId: String, name: String, salts: (Data, Data)) async throws -> PasskeyResponse {
        try await authenticator.register(rpId: rpId, name: name, userID: Self.random(32), salts: salts)
    }

    /// The account outputs of a registration: as returned, after one pinned fallback assertion, or `prfUnavailable`.
    func complete(_ registration: PasskeyResponse, rpId: String, salts: (Data, Data)) async throws -> Result {
        switch Mera.Ceremony.afterRegistration(supported: registration.prfSupported, first: registration.first, second: registration.second) {
        case .prfUnavailable:
            throw Failure.prfUnavailable
        case .assertPinned:
            let fallback = try await assert(rpId: rpId, salts: salts, pinnedTo: registration.credentialID)
            return Result(credentialID: fallback.credentialID, userID: registration.userID ?? fallback.userID, account: fallback.account, utility: fallback.utility)
        case .adopt(let account, let utility):
            return Result(credentialID: registration.credentialID, userID: registration.userID, account: account, utility: utility)
        }
    }

    /// An assertion over both salts: discoverable (no allowCredentials) when `credentialID` is nil, otherwise pinned to
    /// that credential, which must be the one that answers.
    func assert(rpId: String, salts: (Data, Data), pinnedTo credentialID: Data?) async throws -> Result {
        let response = try await authenticator.assert(rpId: rpId, salts: salts, credentialID: credentialID)
        if let credentialID, response.credentialID != credentialID { throw Failure.wrongCredential }
        guard case .adopt(let account, let utility) = Mera.Ceremony.afterAssertion(first: response.first, second: response.second) else {
            throw Failure.prfUnavailable
        }
        return Result(credentialID: response.credentialID, userID: response.userID, account: account, utility: utility)
    }

    /// The utility output alone, for an account whose unlocking ceremony didn't return it. Pinned to `credentialID`,
    /// and the utility salt goes FIRST: a provider that evaluates a single salt still returns it (a PRF output depends
    /// only on the salt, not on its position). The account output comes back second when the provider evaluates both,
    /// so the caller can check it still derives the account's address.
    func utility(rpId: String, salts: (account: Data, utility: Data), pinnedTo credentialID: Data) async throws -> (utility: Data, account: Data?) {
        let response = try await authenticator.assert(rpId: rpId, salts: (salts.utility, salts.account), credentialID: credentialID)
        guard response.credentialID == credentialID else { throw Failure.wrongCredential }
        guard let utility = Mera.Ceremony.usable(response.first) else { throw MeraSession.Failure.noUtilityNamespace }
        return (utility, Mera.Ceremony.usable(response.second))
    }

    /// The Failure an AuthenticationServices error means (MERA-PLAN §2): canceled → cancelled, failed →
    /// associationUnavailable, anything else generic. The system's reason goes to the log in DEBUG builds only.
    static func failure(for error: Error) -> Failure {
        let ns = error as NSError
        let kind: Mera.Ceremony.FailureKind = ns.domain == ASAuthorizationError.errorDomain ? Mera.Ceremony.failureKind(authorizationErrorCode: ns.code) : .other
        #if DEBUG
        if kind != .cancelled {
            let reason = ns.userInfo[NSLocalizedFailureReasonErrorKey] as? String ?? ns.localizedDescription
            Logger(subsystem: "fun.dyorhq.app", category: "passkey").error("passkey ceremony failed (\(ns.domain, privacy: .public) \(ns.code)): \(reason, privacy: .public)")
        }
        #endif
        switch kind {
        case .cancelled: return .cancelled
        case .associationUnavailable: return .associationUnavailable
        case .other: return .failed
        }
    }

    static func random(_ count: Int) -> Data { Data((0..<count).map { _ in UInt8.random(in: 0...255) }) }
}

/// The real authenticator: Apple's ASAuthorizationController with a platform passkey provider.
@MainActor
final class SystemPasskeyAuthenticator: NSObject, PasskeyAuthenticator, ASAuthorizationControllerDelegate, ASAuthorizationControllerPresentationContextProviding {
    private var continuation: CheckedContinuation<PasskeyResponse, Error>?
    /// Held until the request completes, so the controller outlives `perform`.
    private var controller: ASAuthorizationController?

    func register(rpId: String, name: String, userID: Data, salts: (Data, Data)) async throws -> PasskeyResponse {
        let provider = ASAuthorizationPlatformPublicKeyCredentialProvider(relyingPartyIdentifier: rpId)
        let request = provider.createCredentialRegistrationRequest(challenge: PasskeyCeremony.random(32), name: name, userID: userID)
        request.userVerificationPreference = .required
        request.prf = .inputValues(.saltInput1(salts.0, saltInput2: salts.1))
        let response = try await perform(request)
        // A registration result doesn't echo the user handle; it is the one this request set.
        return PasskeyResponse(credentialID: response.credentialID, userID: userID, prfSupported: response.prfSupported, first: response.first, second: response.second)
    }

    func assert(rpId: String, salts: (Data, Data), credentialID: Data?) async throws -> PasskeyResponse {
        let provider = ASAuthorizationPlatformPublicKeyCredentialProvider(relyingPartyIdentifier: rpId)
        let request = provider.createCredentialAssertionRequest(challenge: PasskeyCeremony.random(32))
        request.userVerificationPreference = .required
        request.prf = .inputValues(.saltInput1(salts.0, saltInput2: salts.1))
        if let credentialID { request.allowedCredentials = [ASAuthorizationPlatformPublicKeyCredentialDescriptor(credentialID: credentialID)] }
        return try await perform(request)
    }

    /// One request at a time: a second one while a continuation is pending would replace it, and the first caller
    /// would never resume. `PasskeyCeremony.exclusive` normally stops that earlier; this is the last line.
    private func perform(_ request: ASAuthorizationRequest) async throws -> PasskeyResponse {
        guard continuation == nil else { throw Mera.Ceremony.Busy() }
        let controller = ASAuthorizationController(authorizationRequests: [request])
        controller.delegate = self
        controller.presentationContextProvider = self
        self.controller = controller
        return try await withCheckedThrowingContinuation { continuation in
            self.continuation = continuation
            controller.performRequests()
        }
    }

    private func finish(_ result: Swift.Result<PasskeyResponse, Error>) {
        let continuation = self.continuation
        self.continuation = nil
        controller = nil
        continuation?.resume(with: result)
    }

    private static func bytes(_ key: SymmetricKey?) -> Data? { key?.withUnsafeBytes { Data($0) } }

    // MARK: ASAuthorizationControllerDelegate

    func authorizationController(controller: ASAuthorizationController, didCompleteWithAuthorization authorization: ASAuthorization) {
        switch authorization.credential {
        case let registration as ASAuthorizationPlatformPublicKeyCredentialRegistration:
            finish(.success(PasskeyResponse(credentialID: registration.credentialID, userID: nil, prfSupported: registration.prf?.isSupported,
                                            first: Self.bytes(registration.prf?.first), second: Self.bytes(registration.prf?.second))))
        case let assertion as ASAuthorizationPlatformPublicKeyCredentialAssertion:
            finish(.success(PasskeyResponse(credentialID: assertion.credentialID, userID: assertion.userID, prfSupported: nil,
                                            first: Self.bytes(assertion.prf?.first), second: Self.bytes(assertion.prf?.second))))
        default:
            finish(.failure(PasskeyCeremony.Failure.failed))
        }
    }

    func authorizationController(controller: ASAuthorizationController, didCompleteWithError error: Error) {
        finish(.failure(PasskeyCeremony.failure(for: error)))
    }

    // MARK: ASAuthorizationControllerPresentationContextProviding

    func presentationAnchor(for controller: ASAuthorizationController) -> ASPresentationAnchor {
        let scenes = UIApplication.shared.connectedScenes.compactMap { $0 as? UIWindowScene }
        return scenes.flatMap(\.windows).first { $0.isKeyWindow } ?? scenes.first?.windows.first ?? ASPresentationAnchor()
    }
}

/// Where this build's passkey ceremonies and signals go: the system in every build, except a DEBUG Simulator build
/// launched with `-MeraStubAuthenticator`, which uses the stub (StubPasskeyAuthenticator.swift, absent from Release).
@MainActor
struct PasskeyBackend {
    let authenticator: any PasskeyAuthenticator
    let signal: any PasskeySignaling
    #if DEBUG && targetEnvironment(simulator)
    /// Simulator test mode: the stub answers the ceremonies, so every account they derive is confined to the local fork
    /// where `MeraSession` signs (`Mera.Stub.permits`). Absent from any other build, like the stub.
    var isStub = false
    #endif

    static func forThisBuild(rpcURLs: [URL]) -> PasskeyBackend {
        #if DEBUG && targetEnvironment(simulator)
        if let mode = StubPasskeyAuthenticator.requestedMode {
            let stub = StubPasskeyAuthenticator(mode: mode, rpcURLs: rpcURLs)
            return PasskeyBackend(authenticator: stub, signal: stub, isStub: true)
        }
        #endif
        return PasskeyBackend(authenticator: SystemPasskeyAuthenticator(), signal: SystemPasskeySignal())
    }
}
