// Generated by scripts/dev/lookalike-letters.py: do not edit by hand.
// Source: Unicode confusables.txt (UTS #39), Unicode 16.0, as compiled into ICU 76.1 (macOS libicucore).

/// The letters of other scripts drawn like one ASCII letter or digit, by Unicode's confusables data (UTS #39): each
/// letter or digit of every script but Latin whose skeleton is one ASCII letter or digit (with only combining marks after
/// it) — Cyrillic, Greek, Coptic, Armenian, Cherokee, Lisu, Hebrew, Arabic, Myanmar, Tifinagh, Ethiopic, Canadian
/// syllabics and more; full-width and mathematical letters, which compatibility folding already makes ASCII, left out —
/// and each Latin letter outside ASCII whose skeleton is exactly one (dotless ı, small capital ᴏ, script ɡ; never an
/// accented letter). 833 in all. `WalletHoldings.visible` reads each as that letter, a digit (a Devanagari ०, an
/// Arabic-Indic ٥) only where whole symbols and names are compared: where one is found inside other text, a digit is
/// read as its value, which is no letter (`WalletHoldings.Digits`). `SymbolSafety` counts a letter from outside the
/// everyday Latin letters as a letter that can pass for a Latin one.
enum LookAlikeLetters {
    static let confusables: [(UInt32, Character)] = [
        // Greek And Coptic.
        (0x037A, "i"), (0x037F, "J"), (0x0386, "A"), (0x0388, "E"), (0x0389, "H"), (0x038A, "l"), (0x038C, "O"),
        (0x038E, "Y"), (0x0390, "i"), (0x0391, "A"), (0x0392, "B"), (0x0395, "E"), (0x0396, "Z"), (0x0397, "H"),
        (0x0398, "O"), (0x0399, "l"), (0x039A, "K"), (0x039C, "M"), (0x039D, "N"), (0x039F, "O"), (0x03A1, "P"),
        (0x03A4, "T"), (0x03A5, "Y"), (0x03A7, "X"), (0x03AA, "l"), (0x03AB, "Y"), (0x03AC, "a"), (0x03AE, "n"),
        (0x03AF, "i"), (0x03B0, "u"), (0x03B1, "a"), (0x03B3, "y"), (0x03B7, "n"), (0x03B8, "O"), (0x03B9, "i"),
        (0x03BD, "v"), (0x03BF, "o"), (0x03C1, "p"), (0x03C3, "o"), (0x03C5, "u"), (0x03CA, "i"), (0x03CB, "u"),
        (0x03CC, "o"), (0x03CD, "u"), (0x03D1, "O"), (0x03D2, "Y"), (0x03D3, "Y"), (0x03D4, "Y"), (0x03DC, "F"),
        (0x03E8, "2"), (0x03F1, "p"), (0x03F2, "c"), (0x03F3, "j"), (0x03F4, "O"), (0x03F9, "C"), (0x03FA, "M"),
        // Cyrillic.
        (0x0400, "E"), (0x0401, "E"), (0x0405, "S"), (0x0406, "l"), (0x0407, "l"), (0x0408, "J"), (0x040C, "K"),
        (0x040E, "Y"), (0x0410, "A"), (0x0411, "b"), (0x0412, "B"), (0x0415, "E"), (0x0417, "3"), (0x041A, "K"),
        (0x041C, "M"), (0x041D, "H"), (0x041E, "O"), (0x0420, "P"), (0x0421, "C"), (0x0422, "T"), (0x0423, "Y"),
        (0x0425, "X"), (0x042C, "b"), (0x0430, "a"), (0x0431, "6"), (0x0433, "r"), (0x0435, "e"), (0x043E, "o"),
        (0x0440, "p"), (0x0441, "c"), (0x0443, "y"), (0x0445, "x"), (0x0450, "e"), (0x0451, "e"), (0x0453, "r"),
        (0x0455, "s"), (0x0456, "i"), (0x0457, "i"), (0x0458, "j"), (0x045B, "h"), (0x045E, "y"), (0x0461, "w"),
        (0x0462, "b"), (0x0463, "b"), (0x0472, "O"), (0x0473, "o"), (0x0474, "V"), (0x0475, "v"), (0x0476, "V"),
        (0x0477, "v"), (0x047D, "w"), (0x048C, "b"), (0x048D, "b"), (0x0493, "r"), (0x0498, "3"), (0x049A, "K"),
        (0x049E, "K"), (0x04A2, "H"), (0x04AA, "C"), (0x04AB, "c"), (0x04AC, "T"), (0x04AE, "Y"), (0x04AF, "y"),
        (0x04B0, "Y"), (0x04B1, "y"), (0x04B2, "X"), (0x04BB, "h"), (0x04BD, "e"), (0x04BF, "e"), (0x04C0, "l"),
        (0x04C7, "H"), (0x04C9, "H"), (0x04CD, "M"), (0x04CF, "i"), (0x04D0, "A"), (0x04D1, "a"), (0x04D2, "A"),
        (0x04D3, "a"), (0x04D6, "E"), (0x04D7, "e"), (0x04DE, "3"), (0x04E0, "3"), (0x04E6, "O"), (0x04E7, "o"),
        (0x04E8, "O"), (0x04E9, "o"), (0x04EA, "O"), (0x04EB, "o"), (0x04EE, "Y"), (0x04EF, "y"), (0x04F0, "Y"),
        (0x04F1, "y"), (0x04F2, "Y"), (0x04F3, "y"),
        // Cyrillic Supplement.
        (0x0501, "d"), (0x050C, "G"), (0x051B, "q"), (0x051C, "W"), (0x051D, "w"),
        // Armenian.
        (0x054D, "U"), (0x054F, "S"), (0x0555, "O"), (0x0561, "w"), (0x0563, "q"), (0x0566, "q"), (0x0570, "h"),
        (0x0578, "n"), (0x057C, "n"), (0x057D, "u"), (0x0581, "g"), (0x0584, "f"), (0x0585, "o"),
        // Hebrew.
        (0x05D5, "l"), (0x05D8, "v"), (0x05DF, "l"), (0x05E1, "o"),
        // Arabic.
        (0x0622, "l"), (0x0623, "l"), (0x0625, "l"), (0x0627, "l"), (0x0647, "o"), (0x0661, "l"), (0x0665, "o"),
        (0x0667, "V"), (0x0673, "l"), (0x06BE, "o"), (0x06C0, "o"), (0x06C1, "o"), (0x06C2, "o"), (0x06D5, "o"),
        (0x06F1, "l"), (0x06F5, "o"), (0x06F7, "V"), (0x06FF, "o"),
        // NKo.
        (0x07C0, "O"), (0x07CA, "l"),
        // Devanagari.
        (0x0966, "o"),
        // Bengali.
        (0x09E6, "O"), (0x09EA, "8"), (0x09ED, "9"),
        // Gurmukhi.
        (0x0A66, "o"), (0x0A67, "9"), (0x0A6A, "8"),
        // Gujarati.
        (0x0AE6, "o"),
        // Oriya.
        (0x0B20, "O"), (0x0B66, "O"), (0x0B68, "9"),
        // Tamil.
        (0x0BE6, "o"),
        // Telugu.
        (0x0C66, "o"),
        // Kannada.
        (0x0CE6, "o"),
        // Malayalam.
        (0x0D20, "o"), (0x0D66, "o"), (0x0D6D, "9"),
        // Thai.
        (0x0E50, "o"),
        // Lao.
        (0x0ED0, "o"),
        // Myanmar.
        (0x1010, "o"), (0x101D, "o"), (0x1040, "o"),
        // Georgian.
        (0x10E7, "y"), (0x10FF, "o"),
        // Ethiopic.
        (0x1200, "U"), (0x12D0, "O"),
        // Cherokee.
        (0x13A0, "D"), (0x13A1, "R"), (0x13A2, "T"), (0x13A5, "i"), (0x13A9, "Y"), (0x13AA, "A"), (0x13AB, "J"),
        (0x13AC, "E"), (0x13B3, "W"), (0x13B7, "M"), (0x13BB, "H"), (0x13BD, "Y"), (0x13BE, "O"), (0x13C0, "G"),
        (0x13C2, "h"), (0x13C3, "Z"), (0x13CC, "U"), (0x13CE, "4"), (0x13CF, "b"), (0x13D2, "R"), (0x13D4, "W"),
        (0x13D5, "S"), (0x13D9, "V"), (0x13DA, "S"), (0x13DE, "L"), (0x13DF, "C"), (0x13E2, "P"), (0x13E6, "K"),
        (0x13E7, "d"), (0x13EB, "O"), (0x13EE, "6"), (0x13F2, "h"), (0x13F3, "G"), (0x13F4, "B"),
        // Unified Canadian Aboriginal Syllabics.
        (0x142F, "V"), (0x144C, "U"), (0x146D, "P"), (0x146F, "d"), (0x1472, "b"), (0x1473, "b"), (0x148D, "J"),
        (0x14AA, "L"), (0x14BF, "2"), (0x1541, "x"), (0x157C, "H"), (0x157D, "x"), (0x1587, "R"), (0x15AF, "b"),
        (0x15B4, "F"), (0x15C5, "A"), (0x15DE, "D"), (0x15EA, "D"), (0x15F0, "M"), (0x15F7, "B"),
        // Runic.
        (0x16B7, "X"), (0x16C1, "l"), (0x16D5, "K"), (0x16D6, "M"),
        // Greek Extended.
        (0x1F00, "a"), (0x1F01, "a"), (0x1F02, "a"), (0x1F03, "a"), (0x1F04, "a"), (0x1F05, "a"), (0x1F06, "a"),
        (0x1F07, "a"), (0x1F08, "A"), (0x1F09, "A"), (0x1F0A, "A"), (0x1F0B, "A"), (0x1F0C, "A"), (0x1F0D, "A"),
        (0x1F0E, "A"), (0x1F0F, "A"), (0x1F18, "E"), (0x1F19, "E"), (0x1F1A, "E"), (0x1F1B, "E"), (0x1F1C, "E"),
        (0x1F1D, "E"), (0x1F20, "n"), (0x1F21, "n"), (0x1F22, "n"), (0x1F23, "n"), (0x1F24, "n"), (0x1F25, "n"),
        (0x1F26, "n"), (0x1F27, "n"), (0x1F28, "H"), (0x1F29, "H"), (0x1F2A, "H"), (0x1F2B, "H"), (0x1F2C, "H"),
        (0x1F2D, "H"), (0x1F2E, "H"), (0x1F2F, "H"), (0x1F30, "i"), (0x1F31, "i"), (0x1F32, "i"), (0x1F33, "i"),
        (0x1F34, "i"), (0x1F35, "i"), (0x1F36, "i"), (0x1F37, "i"), (0x1F38, "l"), (0x1F39, "l"), (0x1F3A, "l"),
        (0x1F3B, "l"), (0x1F3C, "l"), (0x1F3D, "l"), (0x1F3E, "l"), (0x1F3F, "l"), (0x1F40, "o"), (0x1F41, "o"),
        (0x1F42, "o"), (0x1F43, "o"), (0x1F44, "o"), (0x1F45, "o"), (0x1F48, "O"), (0x1F49, "O"), (0x1F4A, "O"),
        (0x1F4B, "O"), (0x1F4C, "O"), (0x1F4D, "O"), (0x1F50, "u"), (0x1F51, "u"), (0x1F52, "u"), (0x1F53, "u"),
        (0x1F54, "u"), (0x1F55, "u"), (0x1F56, "u"), (0x1F57, "u"), (0x1F59, "Y"), (0x1F5B, "Y"), (0x1F5D, "Y"),
        (0x1F5F, "Y"), (0x1F70, "a"), (0x1F71, "a"), (0x1F74, "n"), (0x1F75, "n"), (0x1F76, "i"), (0x1F77, "i"),
        (0x1F78, "o"), (0x1F79, "o"), (0x1F7A, "u"), (0x1F7B, "u"), (0x1F80, "a"), (0x1F81, "a"), (0x1F82, "a"),
        (0x1F83, "a"), (0x1F84, "a"), (0x1F85, "a"), (0x1F86, "a"), (0x1F87, "a"), (0x1F88, "A"), (0x1F89, "A"),
        (0x1F8A, "A"), (0x1F8B, "A"), (0x1F8C, "A"), (0x1F8D, "A"), (0x1F8E, "A"), (0x1F8F, "A"), (0x1F90, "n"),
        (0x1F91, "n"), (0x1F92, "n"), (0x1F93, "n"), (0x1F94, "n"), (0x1F95, "n"), (0x1F96, "n"), (0x1F97, "n"),
        (0x1F98, "H"), (0x1F99, "H"), (0x1F9A, "H"), (0x1F9B, "H"), (0x1F9C, "H"), (0x1F9D, "H"), (0x1F9E, "H"),
        (0x1F9F, "H"), (0x1FB0, "a"), (0x1FB1, "a"), (0x1FB2, "a"), (0x1FB3, "a"), (0x1FB4, "a"), (0x1FB6, "a"),
        (0x1FB7, "a"), (0x1FB8, "A"), (0x1FB9, "A"), (0x1FBA, "A"), (0x1FBB, "A"), (0x1FBC, "A"), (0x1FBE, "i"),
        (0x1FC2, "n"), (0x1FC3, "n"), (0x1FC4, "n"), (0x1FC6, "n"), (0x1FC7, "n"), (0x1FC8, "E"), (0x1FC9, "E"),
        (0x1FCA, "H"), (0x1FCB, "H"), (0x1FCC, "H"), (0x1FD0, "i"), (0x1FD1, "i"), (0x1FD2, "i"), (0x1FD3, "i"),
        (0x1FD6, "i"), (0x1FD7, "i"), (0x1FD8, "l"), (0x1FD9, "l"), (0x1FDA, "l"), (0x1FDB, "l"), (0x1FE0, "u"),
        (0x1FE1, "u"), (0x1FE2, "u"), (0x1FE3, "u"), (0x1FE4, "p"), (0x1FE5, "p"), (0x1FE6, "u"), (0x1FE7, "u"),
        (0x1FE8, "Y"), (0x1FE9, "Y"), (0x1FEA, "Y"), (0x1FEB, "Y"), (0x1FEC, "P"), (0x1FF8, "O"), (0x1FF9, "O"),
        // Letterlike Symbols.
        (0x210F, "h"), (0x212B, "A"), (0x213D, "y"),
        // Coptic.
        (0x2C85, "r"), (0x2C8E, "H"), (0x2C92, "l"), (0x2C94, "K"), (0x2C98, "M"), (0x2C9A, "N"), (0x2C9E, "O"),
        (0x2C9F, "o"), (0x2CA2, "P"), (0x2CA3, "p"), (0x2CA4, "C"), (0x2CA5, "c"), (0x2CA6, "T"), (0x2CA8, "Y"),
        (0x2CAC, "X"), (0x2CCA, "9"), (0x2CCC, "3"), (0x2CD0, "L"), (0x2CD2, "6"),
        // Tifinagh.
        (0x2D31, "O"), (0x2D38, "V"), (0x2D39, "E"), (0x2D41, "O"), (0x2D4F, "l"), (0x2D54, "O"), (0x2D55, "Q"),
        (0x2D5D, "X"),
        // Lisu.
        (0xA4D0, "B"), (0xA4D1, "P"), (0xA4D2, "d"), (0xA4D3, "D"), (0xA4D4, "T"), (0xA4D6, "G"), (0xA4D7, "K"),
        (0xA4D9, "J"), (0xA4DA, "C"), (0xA4DC, "Z"), (0xA4DD, "F"), (0xA4DF, "M"), (0xA4E0, "N"), (0xA4E1, "L"),
        (0xA4E2, "S"), (0xA4E3, "R"), (0xA4E6, "V"), (0xA4E7, "H"), (0xA4EA, "W"), (0xA4EB, "X"), (0xA4EC, "Y"),
        (0xA4EE, "A"), (0xA4F0, "E"), (0xA4F2, "l"), (0xA4F3, "O"), (0xA4F4, "U"),
        // Cyrillic Extended B.
        (0xA644, "2"), (0xA647, "i"), (0xA695, "h"),
        // Bamum.
        (0xA6DF, "V"),
        // Cherokee Supplement.
        (0xAB74, "o"), (0xAB75, "i"), (0xAB81, "r"), (0xAB83, "w"), (0xAB8E, "o"), (0xAB93, "z"), (0xAB9C, "u"),
        (0xABA9, "v"), (0xABAA, "s"), (0xABAF, "c"), (0xABBB, "o"),
        // Alphabetic Presentation Forms.
        (0xFB35, "l"), (0xFB38, "v"), (0xFB41, "o"), (0xFB4B, "l"),
        // Arabic Presentation Forms A.
        (0xFBA6, "o"), (0xFBA7, "o"), (0xFBA8, "o"), (0xFBA9, "o"), (0xFBAA, "o"), (0xFBAB, "o"), (0xFBAC, "o"),
        (0xFBAD, "o"), (0xFCD9, "o"), (0xFD3C, "l"), (0xFD3D, "l"),
        // Arabic Presentation Forms B.
        (0xFE87, "l"), (0xFE88, "l"), (0xFE8D, "l"), (0xFE8E, "l"), (0xFEE9, "o"), (0xFEEA, "o"), (0xFEEB, "o"),
        (0xFEEC, "o"),
        // Lycian.
        (0x10282, "B"), (0x10286, "E"), (0x10287, "F"), (0x1028A, "l"), (0x10290, "X"), (0x10292, "O"), (0x10295, "P"),
        (0x10296, "S"), (0x10297, "T"),
        // Carian.
        (0x102A0, "A"), (0x102A1, "B"), (0x102A2, "C"), (0x102A5, "F"), (0x102AB, "O"), (0x102B0, "M"), (0x102B1, "T"),
        (0x102B2, "Y"), (0x102B4, "X"), (0x102CF, "H"),
        // Old Italic.
        (0x10301, "B"), (0x10302, "C"), (0x10309, "l"), (0x10311, "M"), (0x10315, "T"), (0x10317, "X"), (0x1031A, "8"),
        // Deseret.
        (0x10404, "O"), (0x10415, "C"), (0x1041B, "L"), (0x10420, "S"), (0x1042C, "o"), (0x1043D, "c"), (0x10448, "s"),
        // Osage.
        (0x104B4, "R"), (0x104C2, "O"), (0x104CE, "U"), (0x104D2, "7"), (0x104EA, "o"), (0x104F6, "u"),
        // Elbasan.
        (0x10513, "N"), (0x10516, "O"), (0x10518, "K"), (0x1051C, "C"), (0x1051D, "V"), (0x10525, "F"), (0x10526, "L"),
        (0x10527, "X"),
        // Tirhuta.
        (0x114C5, "w"), (0x114D0, "O"),
        // Ahom.
        (0x11706, "v"), (0x1170A, "w"), (0x1170E, "w"), (0x1170F, "w"),
        // Warang Citi.
        (0x118A0, "V"), (0x118A2, "F"), (0x118A3, "L"), (0x118A4, "Y"), (0x118A6, "E"), (0x118A9, "Z"), (0x118AC, "9"),
        (0x118AE, "E"), (0x118AF, "4"), (0x118B2, "L"), (0x118B5, "O"), (0x118B8, "U"), (0x118BB, "5"), (0x118BC, "T"),
        (0x118C0, "v"), (0x118C1, "s"), (0x118C2, "F"), (0x118C3, "i"), (0x118C4, "z"), (0x118C6, "7"), (0x118C8, "o"),
        (0x118CA, "3"), (0x118CC, "9"), (0x118D5, "6"), (0x118D6, "9"), (0x118D7, "o"), (0x118D8, "u"), (0x118DC, "y"),
        (0x118E0, "O"), (0x118E5, "Z"), (0x118E6, "W"), (0x118E9, "C"),
        // Miao.
        (0x16F08, "V"), (0x16F0A, "T"), (0x16F16, "L"), (0x16F28, "l"), (0x16F35, "R"), (0x16F3A, "S"), (0x16F3B, "3"),
        (0x16F40, "A"), (0x16F42, "U"), (0x16F43, "Y"),
        // Mathematical Alphanumeric Symbols.
        (0x1D6A4, "i"), (0x1D6A8, "A"), (0x1D6A9, "B"), (0x1D6AC, "E"), (0x1D6AD, "Z"), (0x1D6AE, "H"), (0x1D6AF, "O"),
        (0x1D6B0, "l"), (0x1D6B1, "K"), (0x1D6B3, "M"), (0x1D6B4, "N"), (0x1D6B6, "O"), (0x1D6B8, "P"), (0x1D6B9, "O"),
        (0x1D6BB, "T"), (0x1D6BC, "Y"), (0x1D6BE, "X"), (0x1D6C2, "a"), (0x1D6C4, "y"), (0x1D6C8, "n"), (0x1D6C9, "O"),
        (0x1D6CA, "i"), (0x1D6CE, "v"), (0x1D6D0, "o"), (0x1D6D2, "p"), (0x1D6D4, "o"), (0x1D6D6, "u"), (0x1D6DD, "O"),
        (0x1D6E0, "p"), (0x1D6E2, "A"), (0x1D6E3, "B"), (0x1D6E6, "E"), (0x1D6E7, "Z"), (0x1D6E8, "H"), (0x1D6E9, "O"),
        (0x1D6EA, "l"), (0x1D6EB, "K"), (0x1D6ED, "M"), (0x1D6EE, "N"), (0x1D6F0, "O"), (0x1D6F2, "P"), (0x1D6F3, "O"),
        (0x1D6F5, "T"), (0x1D6F6, "Y"), (0x1D6F8, "X"), (0x1D6FC, "a"), (0x1D6FE, "y"), (0x1D702, "n"), (0x1D703, "O"),
        (0x1D704, "i"), (0x1D708, "v"), (0x1D70A, "o"), (0x1D70C, "p"), (0x1D70E, "o"), (0x1D710, "u"), (0x1D717, "O"),
        (0x1D71A, "p"), (0x1D71C, "A"), (0x1D71D, "B"), (0x1D720, "E"), (0x1D721, "Z"), (0x1D722, "H"), (0x1D723, "O"),
        (0x1D724, "l"), (0x1D725, "K"), (0x1D727, "M"), (0x1D728, "N"), (0x1D72A, "O"), (0x1D72C, "P"), (0x1D72D, "O"),
        (0x1D72F, "T"), (0x1D730, "Y"), (0x1D732, "X"), (0x1D736, "a"), (0x1D738, "y"), (0x1D73C, "n"), (0x1D73D, "O"),
        (0x1D73E, "i"), (0x1D742, "v"), (0x1D744, "o"), (0x1D746, "p"), (0x1D748, "o"), (0x1D74A, "u"), (0x1D751, "O"),
        (0x1D754, "p"), (0x1D756, "A"), (0x1D757, "B"), (0x1D75A, "E"), (0x1D75B, "Z"), (0x1D75C, "H"), (0x1D75D, "O"),
        (0x1D75E, "l"), (0x1D75F, "K"), (0x1D761, "M"), (0x1D762, "N"), (0x1D764, "O"), (0x1D766, "P"), (0x1D767, "O"),
        (0x1D769, "T"), (0x1D76A, "Y"), (0x1D76C, "X"), (0x1D770, "a"), (0x1D772, "y"), (0x1D776, "n"), (0x1D777, "O"),
        (0x1D778, "i"), (0x1D77C, "v"), (0x1D77E, "o"), (0x1D780, "p"), (0x1D782, "o"), (0x1D784, "u"), (0x1D78B, "O"),
        (0x1D78E, "p"), (0x1D790, "A"), (0x1D791, "B"), (0x1D794, "E"), (0x1D795, "Z"), (0x1D796, "H"), (0x1D797, "O"),
        (0x1D798, "l"), (0x1D799, "K"), (0x1D79B, "M"), (0x1D79C, "N"), (0x1D79E, "O"), (0x1D7A0, "P"), (0x1D7A1, "O"),
        (0x1D7A3, "T"), (0x1D7A4, "Y"), (0x1D7A6, "X"), (0x1D7AA, "a"), (0x1D7AC, "y"), (0x1D7B0, "n"), (0x1D7B1, "O"),
        (0x1D7B2, "i"), (0x1D7B6, "v"), (0x1D7B8, "o"), (0x1D7BA, "p"), (0x1D7BC, "o"), (0x1D7BE, "u"), (0x1D7C5, "O"),
        (0x1D7C8, "p"), (0x1D7CA, "F"),
        // Arabic Mathematical Alphabetic Symbols.
        (0x1EE00, "l"), (0x1EE24, "o"), (0x1EE64, "o"), (0x1EE80, "l"), (0x1EE84, "o"),
        // Latin Extended-A.
        (0x0131, "i"), (0x017F, "f"),
        // Latin Extended-B.
        (0x0184, "b"), (0x018D, "g"), (0x0196, "l"), (0x01A6, "R"), (0x01A7, "2"), (0x01B7, "3"), (0x01BC, "5"),
        (0x01BD, "s"), (0x01C0, "l"), (0x021C, "3"), (0x0222, "8"), (0x0223, "8"),
        // IPA Extensions.
        (0x0251, "a"), (0x0261, "g"), (0x0263, "y"), (0x0269, "i"), (0x026A, "i"), (0x026F, "w"), (0x028B, "u"),
        (0x028F, "y"),
        // Phonetic Extensions.
        (0x1D04, "c"), (0x1D0F, "o"), (0x1D11, "o"), (0x1D1C, "u"), (0x1D20, "v"), (0x1D21, "w"), (0x1D22, "z"),
        (0x1D26, "r"),
        // Phonetic Extensions Supplement.
        (0x1D83, "g"), (0x1D8C, "y"),
        // Latin Extended Additional.
        (0x1E9D, "f"), (0x1EFF, "y"),
        // Latin Extended-D.
        (0xA731, "s"), (0xA75A, "2"), (0xA76A, "3"), (0xA76E, "9"), (0xA798, "F"), (0xA799, "f"), (0xA79F, "u"),
        (0xA7AB, "3"), (0xA7B2, "J"), (0xA7B3, "X"), (0xA7B4, "B"),
        // Latin Extended-E.
        (0xAB32, "e"), (0xAB35, "f"), (0xAB3D, "o"), (0xAB47, "r"), (0xAB48, "r"), (0xAB4E, "u"), (0xAB52, "u"),
        (0xAB5A, "y"),
    ]

    /// The Latin letters drawn as one ASCII letter or digit with a stroke, bar or hook (Ø, Đ, Ł, Ħ, Ɵ, Ʉ), whose
    /// decomposition, if any, doesn't start with that letter, so folding accents leaves them as they are: 82 in
    /// all. They are Latin letters for display safety (`SymbolSafety` doesn't read this table), and
    /// `WalletHoldings.visible` reads each as that letter, so "MØN" and "USĐC" read as MON and USDC.
    static let marked: [(UInt32, Character)] = [
        // Latin-1 Supplement.
        (0x00D0, "D"), (0x00D8, "O"), (0x00F8, "o"),
        // Latin Extended-A.
        (0x0110, "D"), (0x0111, "d"), (0x0126, "H"), (0x0127, "h"), (0x0141, "L"), (0x0142, "l"), (0x0166, "T"),
        (0x0167, "t"),
        // Latin Extended-B.
        (0x0180, "b"), (0x0182, "b"), (0x0183, "b"), (0x0189, "D"), (0x018C, "d"), (0x0191, "F"), (0x0192, "f"),
        (0x0197, "I"), (0x0199, "k"), (0x019A, "l"), (0x019D, "N"), (0x019E, "n"), (0x019F, "O"), (0x01A5, "p"),
        (0x01AD, "t"), (0x01AE, "T"), (0x01B4, "y"), (0x01B5, "Z"), (0x01B6, "z"), (0x01BB, "2"), (0x01E4, "G"),
        (0x01E5, "g"), (0x01EE, "3"), (0x01FE, "O"), (0x01FF, "o"), (0x0224, "Z"), (0x0225, "z"), (0x023C, "c"),
        (0x023E, "T"), (0x0244, "U"), (0x0246, "E"), (0x0247, "e"), (0x0248, "J"), (0x0249, "j"), (0x024D, "r"),
        (0x024E, "Y"), (0x024F, "y"),
        // IPA Extensions.
        (0x0253, "b"), (0x0256, "d"), (0x0257, "d"), (0x0260, "g"), (0x0266, "h"), (0x0268, "i"), (0x026B, "l"),
        (0x026D, "l"), (0x0273, "n"), (0x0275, "o"), (0x027C, "r"), (0x027D, "r"), (0x0282, "s"), (0x0290, "z"),
        (0x02A0, "q"),
        // Phonetic Extensions.
        (0x1D6E, "f"), (0x1D70, "n"), (0x1D72, "r"), (0x1D74, "s"), (0x1D75, "t"), (0x1D76, "z"), (0x1D7B, "i"),
        (0x1D7C, "i"), (0x1D7D, "p"), (0x1D7E, "u"),
        // Latin Extended Additional.
        (0x1E9A, "a"), (0x1E9B, "f"),
        // Latin Extended-C.
        (0x2C67, "H"), (0x2C69, "K"),
        // Latin Extended-D.
        (0xA740, "K"), (0xA74A, "O"), (0xA74B, "o"), (0xA761, "w"),
        // Latin Extended-E.
        (0xAB3E, "o"),
    ]
}
