// Copies the launchpad ABIs from the Foundry build output into a typed TypeScript module for the web app.
// Run `cd contracts && forge build` first, then `node scripts/export-abis.mjs`.
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const contracts = ["LaunchpadFactory", "BondingCurve", "LaunchToken", "FeeEscrow", "HolderFeeSharing", "MemeHook", "LaunchAndBuyRouter"];
const out = [
  "// Generated by scripts/export-abis.mjs from contracts/out. Do not edit by hand.",
];
for (const name of contracts) {
  const artifact = JSON.parse(readFileSync(join(root, "contracts", "out", `${name}.sol`, `${name}.json`), "utf8"));
  const abi = artifact.abi.filter((item) => item.type !== "constructor" && item.type !== "receive" && item.type !== "fallback");
  out.push(`export const ${name}Abi = ${JSON.stringify(abi, null, 2)} as const;`);
}
mkdirSync(join(root, "app", "lib"), { recursive: true });
writeFileSync(join(root, "app", "lib", "abi.ts"), out.join("\n\n") + "\n");
console.log(`wrote app/lib/abi.ts (${contracts.length} ABIs)`);

// Moments (clean-room contracts under contracts/src/moments) go to their own module.
const moments = ["MomentsFactory", "MomentCollect", "MomentVesting", "MomentGraduation", "MomentLocker", "MomentFeeHook", "MomentBuyback", "MomentCoin", "MomentNFT"];
const momentsOut = ["// Generated by scripts/export-abis.mjs from contracts/out. Do not edit by hand."];
for (const name of moments) {
  const artifact = JSON.parse(readFileSync(join(root, "contracts", "out", `${name}.sol`, `${name}.json`), "utf8"));
  const abi = artifact.abi.filter((item) => item.type !== "constructor" && item.type !== "receive" && item.type !== "fallback");
  momentsOut.push(`export const ${name}Abi = ${JSON.stringify(abi, null, 2)} as const;`);
}
writeFileSync(join(root, "app", "lib", "moments-abi.ts"), momentsOut.join("\n\n") + "\n");
console.log(`wrote app/lib/moments-abi.ts (${moments.length} ABIs)`);
